#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""Revsist — Serviço de Catálogo Metodológico e Desenhos de Revisão (Doc 45 §5, §6, §7, §13.2)."""

from typing import List
from app.schemas.protocol import (
    AppraisalInstrumentMeta,
    ConductStandardMeta,
    ProtocolCatalogResponse,
    QuestionFrameworkMeta,
    ReportingGuidelineMeta,
    ReviewDesignMeta,
)

REVIEW_DESIGNS: List[ReviewDesignMeta] = [
    ReviewDesignMeta(
        id="D1",
        name="RS de Efetividade (com ou sem metanálise)",
        when_to_use="Pergunta fechada de efeito de intervenção, tratamento ou política pública.",
        default_framework="PICO",
        default_reporting="PRISMA-2020",
        conduct_standards=["Cochrane/MECIR", "Campbell/MECCIR"],
        critical_appraisal_requirement="obrigatoria",
        expected_synthesis="Quantitativa (metanálise) ou descritiva estruturada",
        registry_eligibility="Elegível a registro prospectivo no PROSPERO",
        suggested_extraction_questions=[
            "Desenho metodológico do estudo primário",
            "Tamanho da amostra / população avaliada",
            "Descrição da intervenção / tratamento aplicado",
            "Comparador / grupo de controle utilizado",
            "Desfecho primário mensurado",
            "Medida de efeito observada e intervalo de confiança",
            "Limitações e vieses declarados pelos autores",
        ],
    ),
    ReviewDesignMeta(
        id="D2",
        name="RS de Prevalência ou Associação",
        when_to_use="Investigação de frequência, incidência, exposição ou fatores de risco/associação em estudos observacionais.",
        default_framework="PECO",
        default_reporting="PRISMA-2020",
        conduct_standards=["JBI", "Cochrane/MECIR"],
        critical_appraisal_requirement="obrigatoria",
        expected_synthesis="Prevalência ponderada ou síntese narrativa agregada",
        registry_eligibility="Elegível a registro prospectivo no PROSPERO",
        suggested_extraction_questions=[
            "Tamanho da população amostrada",
            "Taxa de prevalência / incidência encontrada",
            "Fatores de exposição / determinantes analisados",
            "Critérios de mensuração e instrumentos de coleta",
            "Controle de fatores de confusão",
        ],
    ),
    ReviewDesignMeta(
        id="D3",
        name="Síntese Qualitativa / Metassíntese",
        when_to_use="Compreensão aprofundada de experiências, percepções, significados e contextos socioculturais.",
        default_framework="SPIDER",
        default_reporting="ENTREQ",
        conduct_standards=["JBI meta-agregação"],
        critical_appraisal_requirement="obrigatoria",
        expected_synthesis="Meta-agregação temática ou metaetnografia",
        registry_eligibility="Elegível a registro prospectivo no PROSPERO",
        suggested_extraction_questions=[
            "Abordagem metodológica qualitativa (fenomenologia, teoria fundamentada, etc.)",
            "Contexto sociocultural e institucional",
            "Categorias e temas analíticos identificados",
            "Evidências narrativas e citações ilustrativas",
            "Interpretação e conclusões dos autores",
        ],
    ),
    ReviewDesignMeta(
        id="D4",
        name="Revisão de Escopo (Scoping Review)",
        when_to_use="Mapeamento abrangente da extensão, conceitos-chave, natureza das evidências e lacunas de pesquisa.",
        default_framework="PCC",
        default_reporting="PRISMA-ScR",
        conduct_standards=["JBI", "Arksey & O'Malley + Levac"],
        critical_appraisal_requirement="opcional",
        expected_synthesis="Mapeamento descritivo, tabular e representação gráfica de lacunas",
        registry_eligibility="Registro em repositório aberto (OSF / Figshare) — não aceito pelo PROSPERO",
        suggested_extraction_questions=[
            "População ou participantes caracterizados",
            "Conceito central investigado",
            "Contexto geográfico, setorial ou institucional",
            "Tipo de fonte e desenho metodológico",
            "Principais achados e lacunas identificadas",
        ],
    ),
    ReviewDesignMeta(
        id="D5",
        name="Mapa Sistemático / Mapa de Evidências e Lacunas",
        when_to_use="Catalogação e estruturação visual do corpo de evidências sem estimativa de efeito ou metanálise.",
        default_framework="PCC",
        default_reporting="ROSES",
        conduct_standards=["CEE v5.1"],
        critical_appraisal_requirement="opcional",
        expected_synthesis="Matriz de evidências e mapas de calor de lacunas temáticas",
        registry_eligibility="Depósito em repositório aberto (OSF / CEE)",
        suggested_extraction_questions=[
            "Subtema / Tipo de intervenção",
            "Desfecho ou impacto catalogado",
            "Distribuição geográfica e recorte territorial",
            "Volume e maturidade das evidências disponíveis",
        ],
    ),
    ReviewDesignMeta(
        id="D6",
        name="Revisão de Revisões (Umbrella Review)",
        when_to_use="Síntese e comparação de múltiplas revisões sistemáticas pré-existentes sobre o mesmo objeto de estudo.",
        default_framework="PICO",
        default_reporting="PRIOR",
        conduct_standards=["JBI Umbrella"],
        critical_appraisal_requirement="obrigatoria",
        expected_synthesis="Matriz de sobreposição de estudos primários (CCA) e síntese comparativa",
        registry_eligibility="Elegível a registro prospectivo no PROSPERO",
        suggested_extraction_questions=[
            "Bases de dados consultadas pela revisão incluída",
            "Número e tipos de estudos primários sintetizados",
            "Qualidade metodológica (AMSTAR 2 / ROBIS)",
            "Grau de sobreposição de estudos primários (Corrected Covered Area - CCA)",
            "Consistência das conclusões entre as revisões",
        ],
    ),
    ReviewDesignMeta(
        id="D7",
        name="Revisão Integrativa",
        when_to_use="Integração de literatura teórica, empírica e metodologias diversas para compreensão holística do fenômeno.",
        default_framework="SPIDER",
        default_reporting="PRISMA-2020",
        conduct_standards=["Whittemore & Knafl (2005)", "Souza, Silva & Carvalho (2010)"],
        critical_appraisal_requirement="opcional",
        expected_synthesis="Análise de conteúdo e síntese integrativa de conceitos",
        registry_eligibility="Depósito em repositório aberto (OSF)",
        suggested_extraction_questions=[
            "Referencial teórico adotado",
            "Metodologia empírica empregada",
            "Conceitos e dimensões fundamentais",
            "Implicações para a teoria e para a prática",
        ],
    ),
    ReviewDesignMeta(
        id="D8",
        name="Revisão Rápida (Rapid Review)",
        when_to_use="Síntese ágil de evidências em prazos curtos para subsidiar tomada de decisão e políticas públicas.",
        default_framework="PICO",
        default_reporting="PRISMA-2020",
        conduct_standards=["Cochrane RRMG (Garritty et al. 2021)"],
        critical_appraisal_requirement="opcional",
        expected_synthesis="Síntese narrativa com declaração explícita de atalhos metodológicos",
        registry_eligibility="PROSPERO (com declaração explícita de atalhos e impacto)",
        suggested_extraction_questions=[
            "Atalho metodológico empregado (ex: triagem por 1 revisor, restrição de idioma)",
            "Achados principais sintetizados",
            "Limitações decorrentes do tempo de condução",
        ],
    ),
    ReviewDesignMeta(
        id="D9",
        name="RS em Engenharia de Software (EBSE)",
        when_to_use="Comparação e síntese de tecnologias, métodos, processos, linguagens ou ferramentas de software.",
        default_framework="PICOC",
        default_reporting="EBSE",
        conduct_standards=["Kitchenham & Charters (2007)"],
        critical_appraisal_requirement="obrigatoria",
        expected_synthesis="Agrupamento técnico e análise comparativa de soluções",
        registry_eligibility="Repositório institucional ou aberto",
        suggested_extraction_questions=[
            "Tecnologia / Linguagem / Ferramenta avaliada",
            "Contexto de aplicação (indústria, academia, open-source)",
            "Métricas de qualidade, desempenho ou produtividade",
            "Ameaças à validade identificadas",
        ],
    ),
    ReviewDesignMeta(
        id="D10",
        name="RS em Gestão / Negócios (SPAR-4-SLR)",
        when_to_use="Mapeamento de domínio, teoria, método e proposição de agenda futura em administração e ciências sociais aplicadas.",
        default_framework="CIMO",
        default_reporting="SPAR-4-SLR",
        conduct_standards=["Paul et al. 2021 (SPAR-4-SLR)", "Tranfield, Denyer & Smart 2003"],
        critical_appraisal_requirement="opcional",
        expected_synthesis="Framework TCCM (Theory, Context, Characteristics, Methodology)",
        registry_eligibility="Repositório aberto ou institucional",
        suggested_extraction_questions=[
            "Teoria de suporte (Theory)",
            "Contexto setorial e ambiental (Context)",
            "Características e variáveis investigadas (Characteristics)",
            "Abordagem metodológica (Methodology)",
            "Proposições e agenda futura de pesquisa",
        ],
    ),
    ReviewDesignMeta(
        id="D11",
        name="Estudo Bibliométrico / Cienciométrico",
        when_to_use="Mapeamento da estrutura intelectual, conceitual e social de um campo científico a partir de metadados e citações.",
        default_framework="Domínio-Recorte-Unidade",
        default_reporting="BIBLIO",
        conduct_standards=["Zupic & Čater (2015)", "Donthu et al. (2021)"],
        critical_appraisal_requirement="nao_se_aplica",
        expected_synthesis="Indicadores de produção, redes de coautoria, cocitação, acoplamento bibliográfico e coocorrência de termos",
        registry_eligibility="Depósito em repositório aberto (OSF)",
        suggested_extraction_questions=[
            "Unidade de análise (artigo, autor, instituição, país, periódico)",
            "Autores, filiações e países mais produtivos",
            "Palavras-chave e temas emergentes",
            "Contagem e distribuição de citações",
            "Métricas de rede e clusterização",
        ],
    ),
    ReviewDesignMeta(
        id="D12",
        name="Portfólio Ordenado (Methodi Ordinatio)",
        when_to_use="Seleção e hierarquização multicritério de um portfólio bibliográfico relevante via equação InOrdinatio.",
        default_framework="Livre",
        default_reporting="Generic",
        conduct_standards=["Methodi Ordinatio (Pagani et al. 2015 / 2.0 2022)"],
        critical_appraisal_requirement="opcional",
        expected_synthesis="Ranking ponderado InOrdinatio",
        registry_eligibility="Repositório institucional ou aberto",
        suggested_extraction_questions=[
            "Ano de publicação do estudo",
            "Fator de impacto do periódico (JCR / SJR)",
            "Número de citações acumuladas",
            "Índice InOrdinatio calculado",
        ],
    ),
    ReviewDesignMeta(
        id="D13",
        name="Revisão Narrativa Estruturada",
        when_to_use="Panorama conceitual e teórico amplo com relato estruturado e critérios transparentes de seleção.",
        default_framework="Livre",
        default_reporting="SANRA",
        conduct_standards=[],
        critical_appraisal_requirement="nao_se_aplica",
        expected_synthesis="Síntese narrativa crítica e reflexiva",
        registry_eligibility="Repositório institucional ou aberto",
        suggested_extraction_questions=[
            "Tópico ou dimensão conceitual abordada",
            "Perspectiva teórica dominante",
            "Principais argumentos e controvérsias",
            "Lacunas de conhecimento e reflexões críticas",
        ],
    ),
    ReviewDesignMeta(
        id="D14",
        name="Outro / Híbrido Declarado",
        when_to_use="Combinação metodológica customizada ou abordagem emergente não contemplada pelo catálogo fixo.",
        default_framework="Livre",
        default_reporting="Generic",
        conduct_standards=[],
        critical_appraisal_requirement="opcional",
        expected_synthesis="Síntese customizada conforme declarado no protocolo",
        registry_eligibility="Livre",
        suggested_extraction_questions=[
            "Dados customizados de interesse para a pesquisa",
        ],
    ),
]

REPORTING_GUIDELINES: List[ReportingGuidelineMeta] = [
    ReportingGuidelineMeta(
        id="PRISMA-2020",
        name="PRISMA 2020",
        description="Diretriz canônica para relato de revisões sistemáticas com ou sem metanálise (27 itens).",
        item_count=27,
        reference="Page MJ, McKenzie JE, Bossuyt PM, et al. BMJ 2021;372:n71",
    ),
    ReportingGuidelineMeta(
        id="PRISMA-ScR",
        name="PRISMA-ScR",
        description="Extensão do PRISMA para relato de Revisões de Escopo (22 itens).",
        item_count=22,
        reference="Tricco AC, Lillie E, Zarin W, et al. Ann Intern Med 2018;169(7):467-473",
    ),
    ReportingGuidelineMeta(
        id="PRISMA-P",
        name="PRISMA-P",
        description="Diretriz para elaboração e relato de Protocolos de Revisão Sistemática (17 itens).",
        item_count=17,
        reference="Moher D, Shamseer L, Clarke M, et al. Syst Rev 2015;4:1",
    ),
    ReportingGuidelineMeta(
        id="PRISMA-S",
        name="PRISMA-S",
        description="Extensão do PRISMA para relato completo e transparente de estratégias de busca (16 itens).",
        item_count=16,
        reference="Rethlefsen ML, Kirtley S, Waffenschmidt S, et al. Syst Rev 2021;10:39",
    ),
    ReportingGuidelineMeta(
        id="PRIOR",
        name="PRIOR",
        description="Diretriz de relato para Revisões de Revisões / Umbrella Reviews (27 itens).",
        item_count=27,
        reference="Gates M, Gates A, Pieper D, et al. BMJ 2022;378:e070849",
    ),
    ReportingGuidelineMeta(
        id="ROSES",
        name="ROSES",
        description="Diretriz de relato para sínteses em ciências socioambientais e conservação.",
        item_count=20,
        reference="Haddaway NR, Macura B, Whaley P, Pullin AS. Environ Evid 2018;7:7",
    ),
    ReportingGuidelineMeta(
        id="ENTREQ",
        name="ENTREQ",
        description="Diretriz para relato de sínteses de pesquisa qualitativa (21 itens).",
        item_count=21,
        reference="Tong A, Flemming K, McInnes E, et al. BMC Med Res Methodol 2012;12:181",
    ),
    ReportingGuidelineMeta(
        id="BIBLIO",
        name="BIBLIO",
        description="Diretriz para relato de revisões bibliométricas e cienciométricas estruturadas (20 itens).",
        item_count=20,
        reference="Preliminary guideline for reporting bibliometric reviews. Syst Rev 2023;12:241",
    ),
    ReportingGuidelineMeta(
        id="SANRA",
        name="SANRA",
        description="Escala para avaliação e relato da qualidade de revisões narrativas estruturadas (6 itens).",
        item_count=6,
        reference="Baethge C, Goldbeck-Wood S, Mertens S. Res Integr Peer Rev 2019;4:5",
    ),
    ReportingGuidelineMeta(
        id="Generic",
        name="Checklist Genérica",
        description="Checklist flexível para metodologias híbridas ou customizadas.",
        item_count=10,
        reference="Revsist Generic Checklist",
    ),
]

CONDUCT_STANDARDS: List[ConductStandardMeta] = [
    ConductStandardMeta(
        id="Cochrane/MECIR",
        name="Cochrane Handbook & MECIR",
        organization="Cochrane Collaboration",
        description="Padrões metodológicos estritos para condução de revisões sistemáticas de intervenções.",
        reference="Higgins JPT, et al. Cochrane Handbook for Systematic Reviews of Interventions v6.5, 2024",
    ),
    ConductStandardMeta(
        id="Campbell/MECCIR",
        name="Campbell Collaboration & MECCIR",
        organization="Campbell Collaboration",
        description="Padrões de condução para revisões sistemáticas nas ciências sociais, educação e políticas públicas.",
        reference="Campbell Collaboration Methodological Standards (MECCIR)",
    ),
    ConductStandardMeta(
        id="JBI",
        name="JBI Manual for Evidence Synthesis",
        organization="JBI (Joanna Briggs Institute)",
        description="Manual abrangente para condução de revisões de escopo, qualitativas, prevalência e guarda-chuva.",
        reference="Aromataris E, Lockwood C, Porritt K, et al. JBI Manual for Evidence Synthesis, 2024",
    ),
    ConductStandardMeta(
        id="CEE v5.1",
        name="CEE Guidelines and Standards",
        organization="Collaboration for Environmental Evidence",
        description="Padrões para revisões sistemáticas e mapas de evidências na área ambiental e sustentabilidade.",
        reference="Pullin AS, et al. Guidelines and Standards for Evidence Synthesis in Environmental Management v5.1",
    ),
    ConductStandardMeta(
        id="Kitchenham & Charters",
        name="EBSE Guidelines",
        organization="Evidence-Based Software Engineering",
        description="Diretrizes para realização de revisões sistemáticas da literatura em Engenharia de Software.",
        reference="Kitchenham B, Charters S. Guidelines for performing Systematic Literature Reviews in SE, 2007",
    ),
    ConductStandardMeta(
        id="Paul et al. (SPAR-4-SLR)",
        name="SPAR-4-SLR Protocol",
        organization="International Journal of Consumer Studies",
        description="Protocolo estruturado em 3 estágios (Assembling, Arranging, Assessing) para gestão e negócios.",
        reference="Paul J, Lim WM, O'Cass A, et al. Int J Consum Stud 2021;45(4):O1-O16",
    ),
    ConductStandardMeta(
        id="Methodi Ordinatio",
        name="Methodi Ordinatio (InOrdinatio)",
        organization="UTFPR",
        description="Metodologia multicritério para seleção e ordenação de portfólios bibliográficos.",
        reference="Pagani RN, Kovaleski JL, Resende LM. Scientometrics 2015;105(3):2109-2135 / Qual Quant 2023",
    ),
]

QUESTION_FRAMEWORKS: List[QuestionFrameworkMeta] = [
    QuestionFrameworkMeta(
        id="PICO",
        name="PICO (População, Intervenção, Comparador, Desfecho)",
        components=[
            {"key": "population", "label": "População / Participantes"},
            {"key": "intervention", "label": "Intervenção / Tratamento"},
            {"key": "comparison", "label": "Comparador / Controle"},
            {"key": "outcome", "label": "Desfecho / Resultado"},
        ],
        recommended_for="Revisões de Efetividade e ensaios comparativos",
    ),
    QuestionFrameworkMeta(
        id="PICOS",
        name="PICOS (+ Desenho do Estudo)",
        components=[
            {"key": "population", "label": "População / Participantes"},
            {"key": "intervention", "label": "Intervenção"},
            {"key": "comparison", "label": "Comparador"},
            {"key": "outcome", "label": "Desfecho"},
            {"key": "study_design", "label": "Desenho do Estudo"},
        ],
        recommended_for="Revisões onde o tipo de estudo primário é critério explícito",
    ),
    QuestionFrameworkMeta(
        id="PECO",
        name="PECO (População, Exposição, Comparador, Desfecho)",
        components=[
            {"key": "population", "label": "População"},
            {"key": "exposure", "label": "Exposição / Fator de Risco"},
            {"key": "comparison", "label": "Comparador / Não Expostos"},
            {"key": "outcome", "label": "Desfecho"},
        ],
        recommended_for="Estudos observacionais, epidemiológicos e ambientais",
    ),
    QuestionFrameworkMeta(
        id="PCC",
        name="PCC (População, Conceito, Contexto)",
        components=[
            {"key": "population", "label": "População / Participantes"},
            {"key": "concept", "label": "Conceito Central"},
            {"key": "context", "label": "Contexto / Cenário"},
        ],
        recommended_for="Revisões de Escopo (Scoping Reviews) e Mapas de Evidências",
    ),
    QuestionFrameworkMeta(
        id="SPIDER",
        name="SPIDER (Sample, Phenomenon of Interest, Design, Evaluation, Research type)",
        components=[
            {"key": "sample", "label": "Amostra (Sample)"},
            {"key": "phenomenon", "label": "Fenômeno de Interesse"},
            {"key": "design", "label": "Desenho de Pesquisa"},
            {"key": "evaluation", "label": "Avaliação / Experiência"},
            {"key": "research_type", "label": "Tipo de Pesquisa (Qualitativa/Mista)"},
        ],
        recommended_for="Sínteses qualitativas, metassínteses e estudos mistos",
    ),
    QuestionFrameworkMeta(
        id="SPICE",
        name="SPICE (Setting, Perspective, Intervention, Comparison, Evaluation)",
        components=[
            {"key": "setting", "label": "Cenário (Setting)"},
            {"key": "perspective", "label": "Perspectiva / Stakeholders"},
            {"key": "intervention", "label": "Intervenção / Prática"},
            {"key": "comparison", "label": "Comparador"},
            {"key": "evaluation", "label": "Avaliação de Impacto"},
        ],
        recommended_for="Avaliação de serviços, gestão pública e políticas",
    ),
    QuestionFrameworkMeta(
        id="CIMO",
        name="CIMO (Context, Intervention, Mechanism, Outcome)",
        components=[
            {"key": "context", "label": "Contexto Organizacional/Social"},
            {"key": "intervention", "label": "Intervenção / Ação Gerencial"},
            {"key": "mechanism", "label": "Mecanismo Explicativo"},
            {"key": "outcome", "label": "Desfecho / Impacto"},
        ],
        recommended_for="Pesquisas em Administração, Gestão e Avaliações Realistas",
    ),
    QuestionFrameworkMeta(
        id="Domínio-Recorte-Unidade",
        name="Domínio-Recorte-Unidade (Bibliometria)",
        components=[
            {"key": "domain", "label": "Domínio Temático"},
            {"key": "timeframe", "label": "Recorte Temporal e Geográfico"},
            {"key": "unit", "label": "Unidade de Análise (Artigos, Autores, Redes)"},
        ],
        recommended_for="Estudos bibliométricos e cienciométricos",
    ),
    QuestionFrameworkMeta(
        id="Livre",
        name="Estrutura Livre / Customizada",
        components=[
            {"key": "custom_1", "label": "Componente 1"},
            {"key": "custom_2", "label": "Componente 2"},
        ],
        recommended_for="Projetos interdisciplinares e abordagens não-padronizadas",
    ),
]

APPRAISAL_INSTRUMENTS: List[AppraisalInstrumentMeta] = [
    AppraisalInstrumentMeta(
        id="RoB-2",
        name="Cochrane RoB 2 (Risk of Bias 2)",
        applicable_to="Ensaios Clínicos Randomizados",
        domains=[
            "Processo de randomização",
            "Desvios das intervenções pretendidas",
            "Dados de desfecho ausentes",
            "Mensuração do desfecho",
            "Seleção do resultado relatado",
        ],
        reference="Sterne JAC, et al. BMJ 2019;366:l4898",
    ),
    AppraisalInstrumentMeta(
        id="ROBINS-I",
        name="ROBINS-I (Risk Of Bias In Non-randomized Studies of Interventions)",
        applicable_to="Estudos Não-Randomizados de Intervenção",
        domains=[
            "Confundimento pré-intervenção",
            "Seleção dos participantes",
            "Classificação das intervenções",
            "Desvios das intervenções",
            "Dados ausentes",
            "Mensuração de desfechos",
            "Seleção dos resultados relatados",
        ],
        reference="Sterne JA, et al. BMJ 2016;355:i4919",
    ),
    AppraisalInstrumentMeta(
        id="JBI-Appraisal",
        name="JBI Critical Appraisal Tools",
        applicable_to="Por desenho específico (Coorte, Caso-Controle, Qualitativo, Transversal, etc.)",
        domains=[
            "Validade interna e de amostragem",
            "Adequação metodológica do desenho",
            "Confiabilidade das medições",
            "Análise estatística apropriada",
        ],
        reference="JBI Manual for Evidence Synthesis, 2024",
    ),
    AppraisalInstrumentMeta(
        id="MMAT-2018",
        name="MMAT 2018 (Mixed Methods Appraisal Tool)",
        applicable_to="Estudos de Métodos Mistos, Qualitativos e Quantitativos",
        domains=[
            "Perguntas de triagem inicial",
            "Qualidade da integração de métodos",
            "Adequação da coleta qualitativa e quantitativa",
            "Racionalidade da divergência entre dados",
        ],
        reference="Hong QN, et al. MMAT version 2018",
    ),
    AppraisalInstrumentMeta(
        id="AMSTAR-2",
        name="AMSTAR 2 (A MeaSurement Tool to Assess systematic Reviews)",
        applicable_to="Revisões Sistemáticas de estudos de intervenção (Umbrella Reviews)",
        domains=[
            "Protocolo a priori registrado",
            "Abrangência da busca e literatura cinzenta",
            "Justificativa de exclusão de estudos",
            "Avaliação de risco de viés e metanálise adequada",
        ],
        reference="Shea BJ, et al. BMJ 2017;358:j4008",
    ),
    AppraisalInstrumentMeta(
        id="CASP",
        name="CASP Qualitative Checklist",
        applicable_to="Estudos Qualitativos",
        domains=[
            "Clareza dos objetivos de pesquisa",
            "Adequação da metodologia qualitativa",
            "Relação entre pesquisador e participantes",
            "Rigor na análise dos dados",
        ],
        reference="Critical Appraisal Skills Programme (CASP) 2018",
    ),
    AppraisalInstrumentMeta(
        id="None",
        name="Nenhum Instrumento (Apreciação Opcional Declarada)",
        applicable_to="Revisões de Escopo (D4), Mapas (D5) e Bibliometria (D11)",
        domains=["Declaração formal de não-aplicação conforme item 12 do PRISMA-ScR"],
        reference="PRISMA-ScR Item 12",
    ),
]


def get_full_protocol_catalog() -> ProtocolCatalogResponse:
    """Retorna o catálogo metodológico completo servido pela API."""
    return ProtocolCatalogResponse(
        designs=REVIEW_DESIGNS,
        guidelines=REPORTING_GUIDELINES,
        standards=CONDUCT_STANDARDS,
        frameworks=QUESTION_FRAMEWORKS,
        instruments=APPRAISAL_INSTRUMENTS,
    )


def get_review_design(design_id: str) -> ReviewDesignMeta | None:
    """Recupera metadados de um desenho de revisão por ID (D1..D14)."""
    for d in REVIEW_DESIGNS:
        if d.id.upper() == design_id.upper():
            return d
    return None
