"""ropa: registro das operacoes de tratamento

Cria `processing_records`, o registro que o art. 37 da LGPD exige do
controlador (doc 40 §40.5.2, item L-60 do doc 38).

Tabela nova, sem retrofit: não há como reconstruir o histórico de tratamentos
que já aconteceram, e inventá-lo seria pior do que não tê-lo. O registro começa
aqui e vale daqui para a frente.

`user_id` não é chave estrangeira, de propósito — a razão está no docstring do
modelo, e resumidamente é que o registro precisa sobreviver à eliminação da
conta, já que é ele que prova que a eliminação aconteceu.

Sobre o downgrade
=================
Ele apaga a tabela, e com ela toda a prestação de contas acumulada. Num banco
de desenvolvimento é irrelevante; em produção é a perda da prova de
conformidade, que não se recupera de lugar nenhum. Se a intenção é reverter
código sem perder o registro, reverta só o código: a tabela sobrando não
atrapalha nada.

Revision ID: 1b724bcfc68e
Revises: 2f109e3a4ec7
Create Date: 2026-08-29 19:03:09.089306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b724bcfc68e'
down_revision: Union[str, Sequence[str], None] = '2f109e3a4ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Cria a tabela do ROPA."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('legal_basis', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.String(length=300), nullable=False),
    sa.Column('data_categories', sa.Text(), nullable=False),
    sa.Column('recipient', sa.String(length=64), nullable=True),
    sa.Column('international', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_records', schema=None) as batch_op:
        batch_op.create_index('ix_processing_records_occurred', ['occurred_at'], unique=False)
        batch_op.create_index('ix_processing_records_operation', ['operation'], unique=False)
        batch_op.create_index('ix_processing_records_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Apaga a tabela do ROPA — e o histórico nela. Ver o cabeçalho."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processing_records', schema=None) as batch_op:
        batch_op.drop_index('ix_processing_records_user')
        batch_op.drop_index('ix_processing_records_operation')
        batch_op.drop_index('ix_processing_records_occurred')

    op.drop_table('processing_records')
    # ### end Alembic commands ###
