"""esquema inicial

Revision ID: 48963bb8d65a
Revises: 
Create Date: 2026-08-27 18:58:26.519804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '48963bb8d65a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('api_keys_encrypted', sa.Text(), nullable=False),
    sa.Column('gemini_api_keys_encrypted', sa.Text(), nullable=False),
    sa.Column('qwen_api_keys_encrypted', sa.Text(), nullable=False),
    sa.Column('local_api_keys_encrypted', sa.Text(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('client_host', sa.String(length=64), nullable=False),
    sa.Column('successful', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_login_attempts_username_time', 'login_attempts', ['username', 'attempted_at'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('methodology', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('inst_token', sa.Text(), nullable=False),
    sa.Column('custom_endpoint', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('deduplication_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('total_raw', sa.Integer(), nullable=False),
    sa.Column('total_unique', sa.Integer(), nullable=False),
    sa.Column('total_duplicates', sa.Integer(), nullable=False),
    sa.Column('sources_breakdown', sa.Text(), nullable=False),
    sa.Column('duplicates_list', sa.Text(), nullable=False),
    sa.Column('report_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dedup_reports_project', 'deduplication_reports', ['project_id'], unique=False)
    op.create_table('harvest_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('descriptors_used', sa.Text(), nullable=False),
    sa.Column('query_parameters', sa.Text(), nullable=False),
    sa.Column('checkpoint', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('records_found', sa.Integer(), nullable=False),
    sa.Column('records_new', sa.Integer(), nullable=False),
    sa.Column('records_duplicate', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('papers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('title_normalized', sa.Text(), nullable=False),
    sa.Column('blocking_key', sa.String(length=120), nullable=False),
    sa.Column('authors', sa.Text(), nullable=False),
    sa.Column('advisor', sa.Text(), nullable=False),
    sa.Column('year', sa.String(length=10), nullable=False),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('research_type', sa.String(length=100), nullable=False),
    sa.Column('institution', sa.Text(), nullable=False),
    sa.Column('journal', sa.Text(), nullable=False),
    sa.Column('download_url', sa.Text(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('observations', sa.Text(), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('pdf_text_extracted', sa.Boolean(), nullable=False),
    sa.Column('pdf_status', sa.String(length=20), nullable=False),
    sa.Column('pdf_resolved_url', sa.Text(), nullable=False),
    sa.Column('pdf_strategy', sa.String(length=40), nullable=False),
    sa.Column('pdf_attempts', sa.Text(), nullable=False),
    sa.Column('pdf_page_count', sa.Integer(), nullable=False),
    sa.Column('pdf_size_bytes', sa.Integer(), nullable=False),
    sa.Column('pdf_sha256', sa.String(length=64), nullable=False),
    sa.Column('pdf_text_chars', sa.Integer(), nullable=False),
    sa.Column('pdf_is_scanned', sa.Boolean(), nullable=False),
    sa.Column('pdf_acquired_at', sa.DateTime(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('merged_into_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_blocking_key'), 'papers', ['blocking_key'], unique=False)
    op.create_index('ix_papers_doi', 'papers', ['doi'], unique=False)
    op.create_index(op.f('ix_papers_is_duplicate'), 'papers', ['is_duplicate'], unique=False)
    op.create_index('ix_papers_project_blocking_key', 'papers', ['project_id', 'blocking_key'], unique=False)
    op.create_index('ix_papers_project_decision', 'papers', ['project_id', 'decision'], unique=False)
    op.create_index('ix_papers_project_doi', 'papers', ['project_id', 'doi'], unique=False)
    op.create_index('ix_papers_project_title_norm', 'papers', ['project_id', 'title_normalized'], unique=False)
    op.create_index('ix_papers_title_normalized', 'papers', ['title_normalized'], unique=False)
    op.create_table('protocols',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('pico_framework', sa.Text(), nullable=False),
    sa.Column('search_descriptors', sa.Text(), nullable=False),
    sa.Column('search_filters', sa.Text(), nullable=False),
    sa.Column('manuscript_sections', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('user_agent', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_sessions_token_hash', 'sessions', ['token_hash'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('ai_provider', sa.String(length=40), nullable=False),
    sa.Column('ai_model', sa.String(length=80), nullable=False),
    sa.Column('ai_context_sha256', sa.String(length=64), nullable=False),
    sa.Column('ai_response_valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('criteria',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('protocol_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_exclusion', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extraction_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('protocol_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=200), nullable=False),
    sa.Column('harvested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paper_sources_unique', 'paper_sources', ['paper_id', 'source_name', 'source_id'], unique=False)
    op.create_table('extraction_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('page_ref', sa.String(length=20), nullable=False),
    sa.Column('source_kind', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['extraction_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_criteria',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('criterion_id', sa.String(length=36), nullable=False),
    sa.Column('value', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['criteria.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_criteria')
    op.drop_table('extraction_answers')
    op.drop_index('ix_paper_sources_unique', table_name='paper_sources')
    op.drop_table('paper_sources')
    op.drop_table('extraction_questions')
    op.drop_table('criteria')
    op.drop_table('audit_logs')
    op.drop_index('ix_sessions_token_hash', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('protocols')
    op.drop_index('ix_papers_title_normalized', table_name='papers')
    op.drop_index('ix_papers_project_title_norm', table_name='papers')
    op.drop_index('ix_papers_project_doi', table_name='papers')
    op.drop_index('ix_papers_project_decision', table_name='papers')
    op.drop_index('ix_papers_project_blocking_key', table_name='papers')
    op.drop_index(op.f('ix_papers_is_duplicate'), table_name='papers')
    op.drop_index('ix_papers_doi', table_name='papers')
    op.drop_index(op.f('ix_papers_blocking_key'), table_name='papers')
    op.drop_table('papers')
    op.drop_table('harvest_runs')
    op.drop_index('ix_dedup_reports_project', table_name='deduplication_reports')
    op.drop_table('deduplication_reports')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('source_credentials')
    op.drop_table('projects')
    op.drop_index('ix_login_attempts_username_time', table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_table('ai_settings')
    # ### end Alembic commands ###
