"""aceite: resumo do texto lido pelo titular

Acrescenta `users.terms_sha256` e **anula os aceites que nunca aconteceram**.

O segundo efeito é o que importa. Até aqui, `_criar_conta_por_google` gravava
`terms_accepted_at = agora` no instante em que a conta nascia, sem que a pessoa
tivesse visto texto nenhum. Isso é pior do que não registrar: registrar um
aceite que não houve fabrica prova, e é exatamente o que desmorona numa
fiscalização.

Toda linha com `terms_accepted_at` preenchido e `terms_sha256` vazio está nessa
situação — o resumo é coluna nova, então nenhum aceite anterior tem um. Essas
linhas voltam a `NULL`, e as pessoas veem a tela de aceite no próximo acesso.
Perde-se uma data que não significava nada; ganha-se um registro que significa.


Revision ID: 5be6edabe4f8
Revises: 1b724bcfc68e
Create Date: 2026-08-29 22:52:38.962196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be6edabe4f8'
down_revision: Union[str, Sequence[str], None] = '1b724bcfc68e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Acrescenta o resumo e limpa os aceites fabricados."""
    # ### commands auto generated by Alembic - please adjust! ###
    # O `server_default` fica, e não é só para a criação: `""` é o valor
    # honesto para "não há aceite registrado", que é a leitura segura — a
    # trava então exige a ciência. Uma inserção que esqueça a coluna erra para
    # o lado certo, em vez de estourar.
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("terms_sha256", sa.String(length=64),
                      nullable=False, server_default="")
        )

    # Anula o aceite fabricado. Ver o cabeçalho.
    op.execute(
        "UPDATE users SET terms_accepted_at = NULL, terms_version = '' "
        "WHERE terms_accepted_at IS NOT NULL AND (terms_sha256 IS NULL OR terms_sha256 = '')"
    )



def downgrade() -> None:
    """Remove a coluna. Os aceites anulados não voltam — nem deveriam."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("terms_sha256")
